// Inline copy/types — duplicated here so each .jsx is self-contained without TS imports.
// Mirror of wrapped/copy.ts.

const COPY_DATA = {
  en: {
    brand: "Noteless", wrappedTitle: "Wrapped",
    coverEyebrow: "Your year in practice",
    coverHeadline: (n) => `${n}, here is your year with Noteless.`,
    notesLabel: "Notes generated",
    hoursLabel: "Hours saved with Noteless",
    consultsLabel: "Consultations Noteless assisted in",
    notesContext: "Every conversation, captured.",
    hoursContext: "Time returned to your practice and your life.",
    consultsContext: "Care delivered, with one less thing on your mind.",
    signoff: "Thank you for choosing Noteless.",
    signoffSub: "Focus, dialogue, and freedom — at the core.",
  },
  de: {
    brand: "Noteless", wrappedTitle: "Jahresrückblick",
    coverEyebrow: "Ihr Praxisjahr",
    coverHeadline: (n) => `${n}, das ist Ihr Jahr mit Noteless.`,
    notesLabel: "Erstellte Notizen",
    hoursLabel: "Mit Noteless eingesparte Stunden",
    consultsLabel: "Konsultationen mit Noteless-Unterstützung",
    notesContext: "Jedes Gespräch, festgehalten.",
    hoursContext: "Zurückgewonnene Zeit für Ihre Praxis und Ihr Leben.",
    consultsContext: "Versorgung geleistet — mit weniger Sorgen.",
    signoff: "Danke, dass Sie sich für Noteless entschieden haben.",
    signoffSub: "Fokus, Dialog und Freiheit — im Kern.",
  },
  fr: {
    brand: "Noteless", wrappedTitle: "Rétrospective",
    coverEyebrow: "Votre année en pratique",
    coverHeadline: (n) => `${n}, voici votre année avec Noteless.`,
    notesLabel: "Notes générées",
    hoursLabel: "Heures économisées avec Noteless",
    consultsLabel: "Consultations assistées par Noteless",
    notesContext: "Chaque échange, consigné.",
    hoursContext: "Du temps rendu à votre pratique et à votre vie.",
    consultsContext: "Des soins délivrés, l'esprit plus léger.",
    signoff: "Merci d'avoir choisi Noteless.",
    signoffSub: "Concentration, dialogue et liberté — au cœur.",
  },
  it: {
    brand: "Noteless", wrappedTitle: "Resoconto",
    coverEyebrow: "Il tuo anno in studio",
    coverHeadline: (n) => `${n}, ecco il tuo anno con Noteless.`,
    notesLabel: "Note generate",
    hoursLabel: "Ore risparmiate con Noteless",
    consultsLabel: "Consultazioni assistite da Noteless",
    notesContext: "Ogni conversazione, registrata.",
    hoursContext: "Tempo restituito alla tua pratica e alla tua vita.",
    consultsContext: "Cure erogate, con un pensiero in meno.",
    signoff: "Grazie per aver scelto Noteless.",
    signoffSub: "Focus, dialogo e libertà — al centro.",
  },
  es: {
    brand: "Noteless", wrappedTitle: "Resumen",
    coverEyebrow: "Tu año en consulta",
    coverHeadline: (n) => `${n}, este es tu año con Noteless.`,
    notesLabel: "Notas generadas",
    hoursLabel: "Horas ahorradas con Noteless",
    consultsLabel: "Consultas asistidas por Noteless",
    notesContext: "Cada conversación, registrada.",
    hoursContext: "Tiempo devuelto a tu consulta y a tu vida.",
    consultsContext: "Atención prestada, con una preocupación menos.",
    signoff: "Gracias por elegir Noteless.",
    signoffSub: "Foco, diálogo y libertad — en el centro.",
  },
  nl: {
    brand: "Noteless", wrappedTitle: "Jaaroverzicht",
    coverEyebrow: "Uw jaar in de praktijk",
    coverHeadline: (n) => `${n}, dit is uw jaar met Noteless.`,
    notesLabel: "Aangemaakte notities",
    hoursLabel: "Uren bespaard met Noteless",
    consultsLabel: "Consulten met Noteless-ondersteuning",
    notesContext: "Elk gesprek, vastgelegd.",
    hoursContext: "Tijd terug voor uw praktijk en uw leven.",
    consultsContext: "Zorg verleend, met één zorg minder.",
    signoff: "Bedankt dat u voor Noteless heeft gekozen.",
    signoffSub: "Focus, dialoog en vrijheid — in de kern.",
  },
  da: {
    brand: "Noteless", wrappedTitle: "Året i praksis",
    coverEyebrow: "Dit år i praksis",
    coverHeadline: (n) => `${n}, her er dit år med Noteless.`,
    notesLabel: "Genererede notater",
    hoursLabel: "Timer sparet med Noteless",
    consultsLabel: "Konsultationer hjulpet af Noteless",
    notesContext: "Hver samtale, dokumenteret.",
    hoursContext: "Tid givet tilbage til din praksis og dit liv.",
    consultsContext: "Behandling leveret, med én ting mindre at tænke på.",
    signoff: "Tak fordi du valgte Noteless.",
    signoffSub: "Få aftenerne tilbage",
  },
  no: {
    brand: "Noteless", wrappedTitle: "Året i praksis",
    coverEyebrow: "Ditt år i praksis",
    coverHeadline: (n) => `${n}, her er ditt år med Noteless.`,
    notesLabel: "Genererte notater",
    hoursLabel: "Timer spart med Noteless",
    consultsLabel: "Konsultasjoner med hjelp fra Noteless",
    notesContext: "Hver samtale, dokumentert.",
    hoursContext: "Tid gitt tilbake til praksisen din og livet ditt.",
    consultsContext: "Behandling levert — med én ting mindre å tenke på.",
    signoff: "Takk for at du valgte Noteless.",
    signoffSub: "Få kveldene tilbake",
  },
};


// May Day overlay copy (per locale). Used by the May Day variant.
const MAYDAY_COPY = {
  en: {
    occasion: "1 May · Labour Day",
    coverEyebrow: "A note for May Day",
    coverHeadline: (n) => `${n}, the work behind the work.`,
    tribute: "To the hours after hours,\nthe call returned at nine,\nthe note finished at ten —\nthank you.",
    notesLabel: "Notes you no longer wrote by hand",
    hoursLabel: "Hours returned to patient care",
    consultsLabel: "Consultations where you were present",
    notesContext: "Documentation, lifted.",
    hoursContext: "Time is the only thing we cannot prescribe.",
    hoursMethod: "Based on a documented saving of 3 minutes per consultation.",
    consultsContext: "Care is still yours. The paperwork was ours.",
    signoff: "On the day of work, rest is the gift.",
    signoffSub: "Solidarity with everyone in practice.",
    peers: {
      eyebrow: "Among your peers",
      label: (s) => `You and ${s} this year`,
      youTag: "You",
      peerTag: (s) => `Median ${s}`,
      notes: "Notes generated",
      hours: "Hours saved",
      minutesPer: "Minutes saved per consultation",
      context: "Drawn from anonymised, consenting Noteless users in the same specialty. Solidarity is a number, too.",
    },
    peersPct: {
      eyebrow: "Among your peers",
      title: (s) => `How you compare with ${s}`,
      ofPeers: "of the median",
      topPercentile: (n) => `top ${n}%`,
      notes: "Notes",
      hours: "Hours saved",
      minutesPer: "Minutes per consult",
      context: (s) => `Compared to the median Noteless ${s} this year. We compute multiples and percentiles, never raw rankings.`,
      better: "ahead of median",
      worse: "below median",
      same: "on par with median",
    },
  },
  de: {
    occasion: "1. Mai · Tag der Arbeit",
    coverEyebrow: "Ein Gruß zum 1. Mai",
    coverHeadline: (n) => `${n}, die Arbeit hinter der Arbeit.`,
    tribute: "Den Stunden nach den Stunden,\ndem Anruf um neun,\ndem Brief um zehn —\ndanke.",
    notesLabel: "Notizen, die Sie nicht mehr schreiben mussten",
    hoursLabel: "Arbeitsstunden, die Ihnen zurückgegeben wurden",
    consultsLabel: "Konsultationen, gemeinsam getragen",
    notesContext: "Dokumentation, abgenommen.",
    hoursContext: "Zeit ist das Einzige, das wir nicht verschreiben können.",
    hoursMethod: "Basierend auf einer dokumentierten Einsparung von 3 Minuten pro Konsultation.",
    consultsContext: "Die Versorgung bleibt Ihre. Den Papierkram haben wir übernommen.",
    signoff: "Am Tag der Arbeit ist Ruhe das Geschenk.",
    signoffSub: "Solidarität mit allen in der Praxis.",
    peers: {
      eyebrow: "Im Vergleich zu Ihren Kolleg:innen",
      label: (s) => `Sie und ${s} in diesem Jahr`,
      youTag: "Sie",
      peerTag: (s) => `Median ${s}`,
      notes: "Erstellte Notizen",
      hours: "Eingesparte Stunden",
      minutesPer: "Minuten pro Konsultation gespart",
      context: "Aus anonymisierten, einwilligenden Noteless-Nutzer:innen derselben Fachrichtung. Solidarität ist auch eine Zahl.",
    },
    peersPct: {
      eyebrow: "Im Vergleich zu Ihren Kolleg:innen",
      title: (s) => `Wie Sie im Vergleich zu ${s} stehen`,
      ofPeers: "des Medians",
      topPercentile: (n) => `obere ${n} %`,
      notes: "Notizen",
      hours: "Eingesparte Stunden",
      minutesPer: "Minuten pro Konsultation",
      context: (s) => `Im Vergleich zum Median der Noteless-${s} in diesem Jahr. Wir berechnen Vielfache und Perzentile, niemals Ranglisten.`,
      better: "über dem Median",
      worse: "unter dem Median",
      same: "auf Höhe des Medians",
    },
  },
  fr: {
    occasion: "1ᵉʳ Mai · Fête du Travail",
    coverEyebrow: "Un mot pour le 1ᵉʳ Mai",
    coverHeadline: (n) => `${n}, le travail derrière le travail.`,
    tribute: "Aux heures après les heures,\nà l'appel rendu à neuf,\nà la note finie à dix —\nmerci.",
    notesLabel: "Notes que vous n'avez plus eu à écrire",
    hoursLabel: "Heures de travail qui vous reviennent",
    consultsLabel: "Consultations portées, ensemble",
    notesContext: "La documentation, allégée.",
    hoursContext: "Le temps est la seule chose que nous ne puissions prescrire.",
    hoursMethod: "Basé sur un gain documenté de 3 minutes par consultation.",
    consultsContext: "Le soin reste le vôtre. La paperasse était la nôtre.",
    signoff: "Au jour du travail, le repos est le cadeau.",
    signoffSub: "Solidarité avec celles et ceux qui exercent.",
    peers: {
      eyebrow: "Parmi vos confrères et consœurs",
      label: (s) => `Vous et les ${s} cette année`,
      youTag: "Vous",
      peerTag: (s) => `Médiane ${s}`,
      notes: "Notes générées",
      hours: "Heures gagnées",
      minutesPer: "Minutes gagnées par consultation",
      context: "À partir d'utilisateurs Noteless anonymisés et consentants de la même spécialité. La solidarité est aussi un chiffre.",
    },
    peersPct: {
      eyebrow: "Parmi vos confrères et consœurs",
      title: (s) => `Votre position par rapport aux ${s}`,
      ofPeers: "de la médiane",
      topPercentile: (n) => `top ${n} %`,
      notes: "Notes",
      hours: "Heures gagnées",
      minutesPer: "Minutes par consultation",
      context: (s) => `Comparé à la médiane des ${s} Noteless cette année. Nous calculons des multiples et des centiles, jamais des classements.`,
      better: "au-dessus de la médiane",
      worse: "en dessous de la médiane",
      same: "au niveau de la médiane",
    },
  },
  it: {
    occasion: "1 Maggio · Festa del Lavoro",
    coverEyebrow: "Un pensiero per il 1° Maggio",
    coverHeadline: (n) => `${n}, il lavoro dietro al lavoro.`,
    tribute: "Alle ore dopo le ore,\nalla chiamata delle nove,\nalla nota delle dieci —\ngrazie.",
    notesLabel: "Note che non hai più dovuto scrivere",
    hoursLabel: "Ore di lavoro che ti tornano",
    consultsLabel: "Consultazioni portate, insieme",
    notesContext: "La documentazione, alleggerita.",
    hoursContext: "Il tempo è l'unica cosa che non possiamo prescrivere.",
    hoursMethod: "Basato su un risparmio documentato di 3 minuti per consultazione.",
    consultsContext: "La cura resta la tua. Le scartoffie erano nostre.",
    signoff: "Nel giorno del lavoro, il riposo è il regalo.",
    signoffSub: "Solidarietà con chi esercita ogni giorno.",
    peers: {
      eyebrow: "Tra i tuoi colleghi",
      label: (s) => `Tu e i ${s} quest'anno`,
      youTag: "Tu",
      peerTag: (s) => `Mediana ${s}`,
      notes: "Note generate",
      hours: "Ore risparmiate",
      minutesPer: "Minuti risparmiati per consultazione",
      context: "Da utenti Noteless anonimizzati e consenzienti della stessa specialità. Anche la solidarietà è un numero.",
    },
    peersPct: {
      eyebrow: "Tra i tuoi colleghi",
      title: (s) => `Il tuo confronto con i ${s}`,
      ofPeers: "della mediana",
      topPercentile: (n) => `top ${n}%`,
      notes: "Note",
      hours: "Ore risparmiate",
      minutesPer: "Minuti per consultazione",
      context: (s) => `Rispetto alla mediana dei ${s} Noteless quest'anno. Calcoliamo multipli e percentili, mai classifiche.`,
      better: "sopra la mediana",
      worse: "sotto la mediana",
      same: "in linea con la mediana",
    },
  },
  es: {
    occasion: "1 de Mayo · Día del Trabajo",
    coverEyebrow: "Una nota para el 1 de Mayo",
    coverHeadline: (n) => `${n}, el trabajo detrás del trabajo.`,
    tribute: "A las horas después de las horas,\na la llamada de las nueve,\na la nota de las diez —\ngracias.",
    notesLabel: "Notas que ya no tuviste que escribir",
    hoursLabel: "Horas de trabajo devueltas a ti",
    consultsLabel: "Consultas llevadas, juntas",
    notesContext: "La documentación, aligerada.",
    hoursContext: "El tiempo es lo único que no podemos recetar.",
    hoursMethod: "Basado en un ahorro documentado de 3 minutos por consulta.",
    consultsContext: "El cuidado sigue siendo tuyo. El papeleo fue nuestro.",
    signoff: "En el día del trabajo, el descanso es el regalo.",
    signoffSub: "Solidaridad con quienes ejercen cada día.",
    peers: {
      eyebrow: "Entre tus colegas",
      label: (s) => `Tú y los ${s} este año`,
      youTag: "Tú",
      peerTag: (s) => `Mediana ${s}`,
      notes: "Notas generadas",
      hours: "Horas ahorradas",
      minutesPer: "Minutos ahorrados por consulta",
      context: "A partir de usuarios de Noteless anonimizados y con consentimiento de la misma especialidad. La solidaridad también es un número.",
    },
    peersPct: {
      eyebrow: "Entre tus colegas",
      title: (s) => `Tu comparación con los ${s}`,
      ofPeers: "de la mediana",
      topPercentile: (n) => `top ${n}%`,
      notes: "Notas",
      hours: "Horas ahorradas",
      minutesPer: "Minutos por consulta",
      context: (s) => `Comparado con la mediana de los ${s} en Noteless este año. Calculamos múltiplos y percentiles, nunca rankings.`,
      better: "por encima de la mediana",
      worse: "por debajo de la mediana",
      same: "en línea con la mediana",
    },
  },
  nl: {
    occasion: "1 mei · Dag van de Arbeid",
    coverEyebrow: "Een woord voor 1 mei",
    coverHeadline: (n) => `${n}, het werk achter het werk.`,
    tribute: "Aan de uren na de uren,\nhet telefoontje om negen,\nde notitie om tien —\ndank u.",
    notesLabel: "Notities die u niet meer hoefde te schrijven",
    hoursLabel: "Werkuren die u terugkrijgt",
    consultsLabel: "Consulten samen gedragen",
    notesContext: "Documentatie, verlicht.",
    hoursContext: "Tijd is het enige wat wij niet kunnen voorschrijven.",
    hoursMethod: "Op basis van een gedocumenteerde besparing van 3 minuten per consult.",
    consultsContext: "De zorg blijft van u. Het papierwerk was van ons.",
    signoff: "Op de dag van de arbeid is rust het cadeau.",
    signoffSub: "Solidariteit met iedereen in de praktijk.",
    peers: {
      eyebrow: "Tussen uw vakgenoten",
      label: (s) => `U en ${s} dit jaar`,
      youTag: "U",
      peerTag: (s) => `Mediaan ${s}`,
      notes: "Aangemaakte notities",
      hours: "Bespaarde uren",
      minutesPer: "Minuten bespaard per consult",
      context: "Op basis van geanonimiseerde, toestemmende Noteless-gebruikers in hetzelfde vakgebied. Solidariteit is ook een getal.",
    },
    peersPct: {
      eyebrow: "Tussen uw vakgenoten",
      title: (s) => `Hoe u zich verhoudt tot ${s}`,
      ofPeers: "van de mediaan",
      topPercentile: (n) => `top ${n}%`,
      notes: "Notities",
      hours: "Bespaarde uren",
      minutesPer: "Minuten per consult",
      context: (s) => `Vergeleken met de mediaan van Noteless-${s} dit jaar. Wij berekenen veelvouden en percentielen, geen ranglijsten.`,
      better: "boven de mediaan",
      worse: "onder de mediaan",
      same: "op de mediaan",
    },
  },
  da: {
    occasion: "1. maj · Arbejdernes kampdag",
    coverEyebrow: "En lille hilsen fra Noteless-teamet",
    coverHeadline: (n) => `${n}, dette er resultatet af vores samarbejde.`,
    tribute: "Til timerne efter timerne,\nopkaldet klokken ni,\nnotatet klokken ti —\ntak.",
    consultsLabel: "Konsultationer vi har lavet sammen",
    hoursLabel: "Tid frigjort til at være kliniker",
    notesLabel: "Konsultationer vi har lavet sammen",
    notesContext: "Dokumentation, lettet.",
    hoursContext: "Timer, sparet.",
    hoursMethod: "Baseret på en dokumenteret besparelse på 3 minutter pr. konsultation.",
    consultsContext: "Behandlingen er stadig din. Papirarbejdet var vores.",
    signoff: "På arbejdets dag er hvilen gaven.",
    signoffSub: "Få aftenerne tilbage",
    summaryEyebrow: "Arbejdernes kampdag",
    summaryTitle: "Et år med mere overskud",
    summaryNotesLabel: "Notater skrevet",
    summaryHoursLabel: "Timer frigjort",
    summaryFootnote: "",
    peers: {
      eyebrow: "Blandt dine kolleger",
      label: (s) => `Du og ${s} i år`,
      youTag: "Du",
      peerTag: (s) => `Median ${s}`,
      notes: "Genererede notater",
      hours: "Sparede timer",
      minutesPer: "Minutter sparet pr. konsultation",
      context: "Baseret på anonymiserede, samtykkende Noteless-brugere i samme speciale. Solidaritet er også et tal.",
    },
    peersPct: {
      eyebrow: "Blandt dine kolleger",
      title: (s) => `Dig, blandt ${s}`,
      topPrefix: "Top",
      youTag: "Dig",
      avgTag: (s) => `Gns. ${s}`,
      notes: "Notater i år",
      consults: "Konsultationer i år",
      hours: "Timer tilbage til patientarbejde",
      context: (s) => `Sammenlignet med gennemsnittet af Noteless-${s} i år. Vi viser percentiler, aldrig ranglister.`,
    },
  },
  no: {
    occasion: "1. mai · Arbeidernes dag",
    coverEyebrow: "En liten hilsen fra Noteless Teamet",
    coverHeadline: (n) => `${n}, takk for arbeidet.`,
    tribute: "Til timene etter timene,\ntelefonen klokka ni,\nnotatet klokka ti —\ntakk.",
    consultsLabel: "Konsultasjoner, båret sammen",
    hoursLabel: "Tid frigjort til å være kliniker",
    notesLabel: "Konsultasjoner, båret sammen",
    notesContext: "Dokumentasjon, lettet.",
    hoursContext: "Timer, spart.",
    hoursMethod: "Basert på en dokumentert besparelse på 3 minutter per konsultasjon.",
    consultsContext: "Behandlingen er fortsatt din. Papirarbeidet var vårt.",
    signoff: "På arbeidets dag er hvilen gaven.",
    signoffSub: "Få kveldene tilbake",
    summaryEyebrow: "Arbeidernes dag",
    summaryTitle: "Et år med mer overskudd",
    summaryNotesLabel: "Notater skrevet",
    summaryHoursLabel: "Timer frigjort",
    summaryFootnote: "",
    peers: {
      eyebrow: "Blant dine kolleger",
      label: (s) => `Du og ${s} i år`,
      youTag: "Du",
      peerTag: (s) => `Median ${s}`,
      notes: "Genererte notater",
      hours: "Sparte timer",
      minutesPer: "Minutter spart per konsultasjon",
      context: "Basert på anonymiserte, samtykkende Noteless-brukere i samme spesialitet. Solidaritet er også et tall.",
    },
    peersPct: {
      eyebrow: "Blandt dine kolleger",
      title: (s) => `Du, blandt ${s}`,
      topPrefix: "Topp",
      youTag: "Du",
      avgTag: (s) => `Snitt ${s}`,
      notes: "Notater i år",
      consults: "Konsultasjoner i år",
      hours: "Timer tilbake til pasientarbeid",
      context: (s) => `Sammenlignet med snittet av Noteless-${s} i år. Vi viser percentiler, aldri rangeringer.`,
    },
  },
};

const LOCALE_TO_BCP = { en:"en-GB", de:"de-DE", fr:"fr-FR", it:"it-IT", es:"es-ES", nl:"nl-NL", da:"da-DK", no:"nb-NO" };
const formatNumber = (n, locale) => new Intl.NumberFormat(LOCALE_TO_BCP[locale] || "en-GB").format(n);

window.COPY_DATA = COPY_DATA;
window.MAYDAY_COPY = MAYDAY_COPY;
window.formatNumber = formatNumber;
